#!/bin/bash

IP=$1
COMP=$2
RUN=$3
BUILD=$4
PROFILE=''

explain() {
    echo "!!make sure both devices have cloned the repo to their home directory to create the folder structure with assets!!"
    echo "ARGUMENT 1:"
    echo "target ip address"

    echo "ARGUMENT 2:"
    echo "debug - copies debug version"
    echo "release - copies release version"

    echo "ARGUMENT 3:"
    echo "c - copy the script"
    echo "r - run the script"
    echo "cr - copy and run the script"

    echo "(optional )ARGUMENT 4:"
    echo "build - build before copying"

    echo "Example:"
    echo "sh scp 192.168.2.2 debug c"

    exit 1
}

case $COMP in
debug)
    PROFILE=debug
    ;;
release)
    PROFILE=release
    ;;
*)
    explain
    ;;
esac

case $BUILD in
build)
    case $COMP in
    debug)
        cargo build
        ;;
    release)
        cargo build --release
        ;;
    esac
    ;;
esac

case $RUN in

r)
    ssh pi@$IP "~/metro_pi/target/$PROFILE/metro_pi"
    ;;
c)
    scp -o LogLevel=VERBOSE target/$PROFILE/metro_pi pi@$IP:~/metro_pi/target/$PROFILE/
    ;;
cr)
    scp -o LogLevel=VERBOSE target/$PROFILE/metro_pi pi@$IP:~/metro_pi/target/$PROFILE/
    ssh pi@$IP "~/metro_pi/target/$PROFILE/metro_pi"
    ;;
*)
    explain
    ;;
esac
