#!/bin/bash

ARG=$1
PW="pi"
# REMOTE=pi@raspberrypi.local

case $ARG in
mkdir)
    sshpass -p $PW ssh -v pi@raspberrypi.local 'mkdir -p ~/build'
    ;;
debug)
    sshpass -p $PW scp -o LogLevel=VERBOSE target/debug/metro_pi pi@raspberrypi.local:~/build/
    ;;
release)
    sshpass -p $PW scp -o LogLevel=VERBOSE target/release/metro_pi pi@raspberrypi.local:~/build/
    ;;
*)

    echo "ARGUMENTS:"
    echo "mkdir - creates build directory on pi"
    echo "debug - copies debug version"
    echo "release - copies release version"
    ;;
esac
