#!/bin/bash

ARG=$1
# IP=$2
# REMOTE=pi@raspberrypi.local

case $ARG in
mkdir)
    ssh -v pi@raspberrypi.local 'mkdir -p ~/build'
    ;;
debug)
    scp -o LogLevel=VERBOSE target/debug/metro_pi pi@raspberrypi.local:~/build/
    # rsync -p -v target/debug/metro_pi pi@raspberrypi.local:~/build/
    ;;
release)
    scp -o LogLevel=VERBOSE target/release/metro_pi pi@raspberrypi.local:~/build/
    ;;
*)

    echo "ARGUMENTS:"
    echo "mkdir - creates build directory on pi"
    echo "debug - copies debug version"
    echo "release - copies release version"
    ;;
esac
